version: "3.8"

services:
  db:
    build: ./sql
    image: marrow-db:latest
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./sql/test_db:/var/lib/mysql

  game:
    build: .
    image: marrow:latest
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "8000:8000"

networks:
  internal: